apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backzacc-ch
  labels:
    app: backzacc-web
spec:
  template:
    metadata:
      labels:
        app: backzacc-web
    spec:
      containers:
      - name: backzacc-ch
        image: myreg/backzacc-ch:latest
        ports:
        - containerPort: 80
          name: backzacc-ch
